version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=YOUR_DB_URL
      - ALPHA_VANTAGE_API_KEY1=YOUR_API_KEY
      - ALPHA_VANTAGE_BASE_URL=https://www.alphavantage.co/query?function=CURRENCY_EXCHANGE_RATE&from_currency={}&to_currency={}&apikey={}
    command: >
      sh -c "while ! nc -z db 3306;
      do
        echo 'Waiting for MySQL...';
        sleep 3;
      done;
      uvicorn app.main:app --host 0.0.0.0 --port 80"

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: YOUR_DB_PW
      MYSQL_DATABASE: YOUR_DB_NAME
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
